services:
  api:
    image: eugenybaz/abm:latest
    container_name: abm_api
    restart: always
    env_file:
      - .env.prod
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    image: eugenybaz/abm:latest
    container_name: abm_bot
    restart: always
    env_file:
      - .env.prod
    command: python -m app.bot.run_bot
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: abm_db
    restart: always
    environment:
      POSTGRES_DB: abm
      POSTGRES_USER: abm
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: